### ISSUE TITLE
Is the project name an intentional reference to recreational inhalation of toluene vapours (toluene is a component of some glues)

### ISSUE THREAD

**Issue by KOLANICH** [kpcyrd/sniffglue#102]

**Comment by kpcyrd** [comment]
hi, thanks for asking!

The name is a reference to [network sniffing](https://en.wikipedia.org/wiki/Packet_sniffer) and [glue code](https://en.wikipedia.org/wiki/Glue_code), the default is human readable output but there's also a `--json` flag that generates a json stream of parsed packets. This stream can be easily ingested by other software that wants to process network packets but doesn't want to implement packet parsing. An example of this would be using `sniffglue --json` in shell scripts together with [`jq`](https://stedolan.github.io/jq/).

I hope this answers your question!
