### ISSUE TITLE
BPF filtering?

### ISSUE THREAD

**Issue by 0b01** [kpcyrd/sniffglue#43]
Does it support bpf filters?

**Comment by kpcyrd** [comment]
Not right now. There is currently no filtering in place besides the various verbose modes that rely on parsing the packets.

Even though the [pcap] crate supports it, I'm planning to migrate to [pnet] eventually (#44), which [doesn't support bpf filtering yet][1], but may have it in the future.

Sorry for that, but I hope it answers your question.

To fully understand your usecase, are you interested in applying your own raw bpf filters or would a higher level filtering language that compiles to bpf work for you as well?

[pcap]: https://docs.rs/pcap/0.7.0/pcap/struct.Capture.html#method.filter
[pnet]: https://github.com/libpnet/libpnet
[1]: https://github.com/libpnet/libpnet/issues/245

**Comment by rickyhan** [comment]
Bpf compiler is a part of libpcap so it is unreasonable to oxidize that entire code base. Applying raw bpf filter is the bottom if you want pure rust.
