### ISSUE TITLE
Fails to compile via cargo install sniffglue

### ISSUE THREAD

**Issue by skickar** [kpcyrd/sniffglue#58]
On MacOS and Ubuntu, the same error preventing installation while running "cargo install sniffglue"

Dell-3:~$ cargo install sniffglue
    Updating crates.io index
  Installing sniffglue v0.9.0
   Compiling libc v0.2.58
   Compiling autocfg v0.1.4
   Compiling rand_core v0.4.0
   Compiling siphasher v0.2.3
   Compiling proc-macro2 v0.4.30
   Compiling memchr v2.2.0
   Compiling unicode-xid v0.1.0
   Compiling typenum v1.10.0
   Compiling version_check v0.1.5
   Compiling byteorder v1.3.2
   Compiling bitflags v1.1.0
   Compiling syn v0.15.38
   Compiling regex v1.1.7
   Compiling unicode-width v0.1.5
   Compiling ryu v0.2.8
   Compiling ucd-util v0.1.3
   Compiling unicode-segmentation v1.3.0
   Compiling serde v1.0.93
   Compiling lazy_static v1.3.0
   Compiling byte-tools v0.3.1
   Compiling pcap v0.7.0
   Compiling strsim v0.8.0
   Compiling vec_map v0.8.1
   Compiling quick-error v1.2.2
   Compiling nix v0.14.1
   Compiling cfg-if v0.1.9
   Compiling utf8-ranges v1.0.3
   Compiling ansi_term v0.11.0
   Compiling termcolor v1.0.5
   Compiling void v1.0.2
   Compiling itoa v0.4.4
   Compiling opaque-debug v0.2.2
   Compiling fake-simd v0.1.2
   Compiling cookie-factory v0.2.4
   Compiling reduce v0.1.2
   Compiling phf_shared v0.7.24
   Compiling rand_core v0.3.1
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling num-traits v0.2.8
   Compiling nom v4.2.3
   Compiling textwrap v0.11.0
   Compiling regex-syntax v0.6.7
   Compiling block-padding v0.1.4
   Compiling thread_local v0.3.6
   Compiling humantime v1.2.0
   Compiling log v0.4.6
   Compiling heck v0.3.1
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling phf v0.7.24
   Compiling rand_os v0.1.3
   Compiling rand_jitter v0.1.4
   Compiling atty v0.2.11
   Compiling time v0.1.42
   Compiling dirs-sys v0.3.3
   Compiling num_cpus v1.10.1
   Compiling users v0.9.1
   Compiling aho-corasick v0.7.3
   Compiling dns-parser v0.8.0
   Compiling base64 v0.10.1
   Compiling clap v2.33.0
   Compiling generic-array v0.12.0
   Compiling threadpool v1.7.1
   Compiling dirs v2.0.1
   Compiling quote v0.6.12
   Compiling dhcp4r v0.1.0
   Compiling rusticata-macros v1.1.0
   Compiling num-traits v0.1.43
   Compiling digest v0.8.0
   Compiling block-buffer v0.7.3
   Compiling enum_primitive v0.1.1
   Compiling sha2 v0.8.0
   Compiling toml v0.5.1
   Compiling serde_json v1.0.39
   Compiling phf_generator v0.7.24
   Compiling phf_codegen v0.7.24
   Compiling tls-parser v0.7.1
   Compiling env_logger v0.6.1
   Compiling structopt-derive v0.2.16
   Compiling serde_derive v1.0.93
   Compiling structopt v0.2.16
   Compiling pktparse v0.4.0
   Compiling sniffglue v0.9.0
error[E0432]: unresolved imports `nix::unistd::getgroups`, `nix::unistd::setgroups`
 --> /Users/skickar/.cargo/registry/src/github.com-1ecc6299db9ec823/sniffglue-0.9.0/src/sandbox/mod.rs:7:45
  |
7 | use nix::unistd::{Uid, Gid, setuid, setgid, getgroups, setgroups};
  |                                             ^^^^^^^^^  ^^^^^^^^^ no `setgroups` in `unistd`
  |                                             |
  |                                             no `getgroups` in `unistd`

error[E0432]: unresolved import `syscallz`
 --> /Users/skickar/.cargo/registry/src/github.com-1ecc6299db9ec823/sniffglue-0.9.0/src/sandbox/error.rs:3:5
  |
3 | use syscallz;
  |     ^^^^^^^^ no `syscallz` in the root

error[E0119]: conflicting implementations of trait `std::convert::From<[type error]>` for type `sandbox::error::Error`:
  --> /Users/skickar/.cargo/registry/src/github.com-1ecc6299db9ec823/sniffglue-0.9.0/src/sandbox/error.rs:23:1
   |
17 | impl From<syscallz::Error> for Error {
   | ------------------------------------ first implementation here
...
23 | impl From<config::Error> for Error {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `sandbox::error::Error`

error[E0119]: conflicting implementations of trait `std::convert::From<[type error]>` for type `sandbox::error::Error`:
  --> /Users/skickar/.cargo/registry/src/github.com-1ecc6299db9ec823/sniffglue-0.9.0/src/sandbox/error.rs:29:1
   |
17 | impl From<syscallz::Error> for Error {
   | ------------------------------------ first implementation here
...
29 | impl From<nix::Error> for Error {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `sandbox::error::Error`

error[E0119]: conflicting implementations of trait `std::convert::From<[type error]>` for type `sandbox::error::Error`:
  --> /Users/skickar/.cargo/registry/src/github.com-1ecc6299db9ec823/sniffglue-0.9.0/src/sandbox/error.rs:35:1
   |
17 | impl From<syscallz::Error> for Error {
   | ------------------------------------ first implementation here
...
35 | impl From<std::io::Error> for Error  {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `sandbox::error::Error`

error: aborting due to 5 previous errors

Some errors occurred: E0119, E0432.
For more information about an error, try `rustc --explain E0119`.
error: failed to compile `sniffglue v0.9.0`, intermediate artifacts can be found at `/var/folders/n1/l_2ynlx91lv57t122lq8lkyh0000gn/T/cargo-installe89ORx`

Caused by:
  Could not compile `sniffglue`.

---------------------------------------------------------

**Comment by kpcyrd** [comment]
hey!

there's currently no OSX support, partially because I ran into issues with the [pcap crate](https://crates.io/crates/pcap) and because I don't own a mac, I would accept patches though.

It should work on ubuntu though, can you please post your `rustc --version`, check if you have `libpcap-dev` and `libseccomp-dev` installed and build log? Thanks!

**Comment by kpcyrd** [comment]
Closing since sniffglue got ported and uploaded to brew in the meantime
