### ISSUE TITLE
Not-quite-live output

### ISSUE THREAD

**Issue by HeapUnderfl0w** [kpcyrd/sniffglue#63]
When using sniffglue to capture packages, output takes an extremly long time to show up.

This is a cast recorded w/o cutting out breaks of the delay between making a request and seeing that request actually show up https://asciinema.org/a/l4MTLV8Qf49D1mUNVSf4oXXEj

Is this "intended behavior"?
Is this a bug?
Is maybe my system misconfigured?(1)

Versions:
- sniffglue: `sniffglue 0.9.0`
- os (arch): `Linux sigma 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux`
- core/libpcap `1.9.1-2`
- core/libseccomp `2.4.1-3`
- rustc `rustc 1.39.0 (4560ea788 2019-11-04)`
- cargo `cargo 1.39.0 (1c6ec66d5 2019-09-30)`

(1): If this is the case then its my fault, but it would be nice to know

**Comment by kpcyrd** [comment]
Thanks for your report. I assume this is due to a recent change in libpcap that requires calling `pcap_set_immediate_mode`. Unfortunately this function isn't exposed by the pcap crate (which seems to be dead unfortunately) https://github.com/ebfull/pcap/pull/55

**Comment by HeapUnderfl0w** [comment]
how thin is the pcap wrapper?
if its a really thin one, you could maybe look into bindgen, to generate direct ffi bindings to libpcap.

**Comment by jepunband** [comment]
i have the same problem....

Listening on device: "wlan1", verbosity 1/4  <-- just waits here....

**Comment by kpcyrd** [comment]
@jepunband Can you post the output of `sniffglue --version` and try increasing the verbosity with `sniffglue -vvv`? Also make sure you're using the right interface.

**Comment by HeapUnderfl0w** [comment]
Also i have already confirmed this working by using the git version. you can try it out using `cargo install --git https://github.com/kpcyrd/sniffglue sniffglue --force`
