### ISSUE TITLE
Installation on WSL fails to run

### ISSUE THREAD

**Issue by djrbeen** [kpcyrd/sniffglue#64]
Hi,
first of all a BIG THANK YOU for sharing your work! 
I'm trying to install sniffglue on WSL every thing goes well without any errors but when I want to run it have this error:

`rbeen@------:~$ sudo .cargo/bin/sniffglue
[sudo] password for rbeen:
thread 'main' panicked at 'init sandbox stage1: Seccomp(Error { inner: "seccomp_load returned error" })', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
rbeen@------:~$`

Can it be fixed?
Thanks in advance!
Best regards,

Rbeen

**Comment by steev** [comment]
Not in WSL1, but it should work on WSL2 which should be generally available with the 2004 release of Windows 10

**Comment by djrbeen** [comment]
Thanks for your answer! I've managed to migrate from WSL1 to WSL2 but when I run sniffglue have this:

`Error: Failed to activate interface: socket: Operation not permitted`

And if I run it with sudo can't find sniffglue script

What to do to fix it?
Thanks!

**Comment by kpcyrd** [comment]
@djrbeen if you used `cargo install` the binary is installed to `~/.cargo/bin/sniffglue`, which is only in the $PATH of the user that ran `cargo install`. If you use `which sniffglue` you get the absolute path that you can run with sudo, it's probably more convenient to either run `sudo cargo install sniffglue`, or copy the binary into a folder that's in root's $PATH, like `/usr/local/bin`.
