### ISSUE TITLE
issues in bench.rs

### ISSUE THREAD

**Issue by plugwash** [kpcyrd/sniffglue#83]
While getting the autopkgtest working in the Debian package I ran into some issues in bench.rs

Firstly IPv4Protocol has been renamed to IPProtocol
and moved to pktparse::ip as part of adding ipv6
support to pktparse.
https://github.com/bestouff/pktparse-rs/commit/ebb468ace109339b9833e0e633494a410549fb41

Secondly centrifuge::parse was renamed to centrifuge::parse_eth in
https://github.com/kpcyrd/sniffglue/commit/2bf3785b275fc2b52ba039fc6a11c91bb4b069f8

Fixes are at https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/sniffglue/debian/patches/fix-bench.patch

**Comment by kpcyrd** [comment]
Thanks!
