### ISSUE TITLE
ppp support

### ISSUE THREAD

**Issue by felixonmars** [kpcyrd/sniffglue#95]
Seems like ppp interfaces are not supported now:

```
$ sniffglue ppp0
Listening on device: "ppp0", verbosity 0/4
Error: Unknown link type: 113 
```

**Comment by kpcyrd** [comment]
hi!

the link type can be added here: https://github.com/kpcyrd/sniffglue/blob/main/src/link.rs

If ppp emits plain ethernet frames it can be added relatively easily here: https://github.com/kpcyrd/sniffglue/blob/7c2c376d815337680d9588269751244f89456360/src/centrifuge/mod.rs#L26

If you have either instructions on how to easily create a ppp device to test with, or a pcap file, that'd be very useful for implementing support. :)

Thanks!"

**Comment by felixonmars** [comment]
[ppp0.pcap.gz](https://github.com/kpcyrd/sniffglue/files/7194935/ppp0.pcap.gz)

I'm not familiar with the internals either, hope this pcap file helps :)
